<template><section class="resources-guide"><header><nuxt-link to="/read">← 返回书库</nuxt-link><div class="intro"><div><small>原木娘的小课堂</small><h1>攒一点原木，为喜欢的作品加油</h1><p>种一棵树、补充余额，或参与社区活动，找到适合你的获取方式。</p></div><img src="/reading/get-logs-guide.png" alt="原木娘种树、充值和参与社区活动" /></div></header><div class="channels"><article v-for="channel in channels" :key="channel.id"><div class="channel-title"><span>{{ channel.number }}</span><h2>{{ channel.title }}</h2><small>{{ channel.tag }}</small></div><p>{{ channel.description }}</p><ol><li v-for="step in channel.steps" :key="step">{{ step }}</li></ol><nuxt-link v-if="channel.to" :to="channel.to">{{ channel.action }} →</nuxt-link><a v-else :href="channel.href" target="_blank" rel="noopener">{{ channel.action }} ↗</a></article></div><aside><h2>把原木送给喜欢的创作者</h2><p>获取原木后，回到作品页选择礼物，就能为喜欢的作品打赏。树场收益、充值额度及活动奖励以对应页面说明为准。</p><nuxt-link to="/read">发现喜欢的作品 →</nuxt-link></aside></section></template>
<script>
import { readingHead } from '~/utils/reading-seo'
export default {
 data:()=>({channels:[
  {id:'tree',number:'01',title:'原木树场种树',tag:'日常积累',description:'从一棵小树苗开始，在自己的树场里培育树木，成熟后收获原木。',steps:['进入原木树场，种下树苗','根据树场提示培育树木，等待成熟','收获树木，原木会加入你的余额'],action:'去树场种树',to:'/read/rewards'},
  {id:'recharge',number:'02',title:'原木充值',tag:'直接补充',description:'想及时支持喜欢的作品，可以通过充值补充原木余额。',steps:['进入充值页面，选择合适的原木额度','确认订单并按照页面提示完成支付','支付成功后，查看原木余额及订单记录','你的充值也将被用于社区维护与运营'],action:'前往原木充值',href:`${process.env.mobileUrl}/#/pages/payments/recharge`},
  {id:'activity',number:'03',title:'参与社区活动',tag:'一起参与',description:'关注社区活动公告，参与设有原木奖励的活动，收获创作与交流的乐趣。',steps:['查看活动消息，了解正在开展的活动','阅读参与条件、截止时间及奖励说明','按照活动规则参与，奖励以活动公告为准'],action:'查看活动消息',to:'/read/activities'}
 ]}),
 head:()=>readingHead({title:'如何获取原木 - 原木社区',description:'通过种树收获、原木充值与社区活动，为喜欢的作品和创作者加油。',path:'/read/resources'})
}
</script>
<style scoped>.resources-guide{max-width:1180px;margin:0 auto;padding:112px 28px 70px;color:#514739}.resources-guide a{color:#778957;text-decoration:none}.intro{display:grid;grid-template-columns:1fr 420px;align-items:center;gap:38px;margin:35px 0}.intro small{color:#8c9c67;font-size:13px}.intro h1{font-size:30px;line-height:1.5;margin:12px 0}.intro p,p{color:#958978;font-size:14px;line-height:1.9}.intro img{width:100%;height:200px;object-fit:contain;border-radius:16px;background:#fffcf4}.channels{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}.channels article{background:white;border:1px solid #e5e6dc;border-radius:13px;padding:24px;display:flex;flex-direction:column;min-width:0}.channel-title{display:flex;align-items:center;gap:9px;flex-wrap:wrap}.channel-title>span{font-size:14px;padding:7px;background:#eef1e4;border-radius:6px;color:#829159}.channel-title h2{font-size:17px;margin:0}.channel-title small{font-size:11px;color:#a39987}.channels ol{padding-left:20px;font-size:13px;line-height:1.9;color:#988c7a;flex:1}.channels li{margin:8px 0}.channels a{font-size:14px;border-top:1px solid #efede5;padding-top:18px;margin-top:10px}aside{margin-top:28px;border:1px solid #e7e5dd;background:#fff;border-radius:13px;padding:24px}aside h2{font-size:17px;margin:0}a:focus-visible{outline:2px solid #8da366;outline-offset:3px}@media(max-width:900px){.intro{grid-template-columns:1fr 280px;gap:20px}.channels{grid-template-columns:1fr}.channels ol{margin-top:0}.intro h1{font-size:25px}}@media(max-width:600px){.resources-guide{padding:100px 18px 50px}.intro{grid-template-columns:1fr;gap:10px}.intro img{height:160px}.intro h1{font-size:24px}.channels article{padding:20px}}
</style>
