CREATE TABLE IF NOT EXISTS image_dominant_colors (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	image_url VARCHAR(512) NOT NULL COMMENT '图片URL',
	dominant_color CHAR(7) DEFAULT NULL COMMENT '主色，格式 #RRGGBB',
	extract_status ENUM('success', 'failed') NOT NULL DEFAULT 'success' COMMENT '提取状态',
	error_message VARCHAR(255) DEFAULT NULL COMMENT '失败原因',
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	UNIQUE KEY uniq_image_url (image_url)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='图片主色缓存表';
