CREATE TABLE IF NOT EXISTS miniapps (
  app_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,
  name VARCHAR(80) NOT NULL,
  icon_url VARCHAR(2048) NOT NULL,
  description VARCHAR(500) NOT NULL DEFAULT '',
  debug_url VARCHAR(2048) NOT NULL,
  production_url VARCHAR(2048) NOT NULL,
  enabled TINYINT NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
