const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),routes=new Map(),calls=[];let query
const router={};for(const verb of ['get','post'])router[verb]=(url,...handlers)=>routes.set(`${verb} ${url}`,handlers.at(-1));const moduleStub={exports:{}}
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../routes/manga-danmu.js'),'utf8'),{module:moduleStub,exports:moduleStub.exports,Date,console,require(s){if(s==='express')return{Router:()=>router};if(s.includes('sql.js'))return{query:async(sql,p)=>{calls.push({sql,p:Array.from(p)});return query(sql,p)}};if(s.includes('readingVisibility'))return require('../bin/readingVisibility');return{}}})
async function invoke(key,patch={}){const res={code:200,status(n){this.code=n;return this},json(data){this.data=data;return this}};await routes.get(key)({query:{id:7,articleId:11},body:{novel_id:7,article_id:11,page_idx:0,content:' Hello '},user:[{user_id:7}],...patch},res);return res}
async function main(){
query=async sql=>sql.includes('SELECT a.article_id')?[{article_id:11,content:'{"pages":[{},{}]}'}]:sql.startsWith('INSERT')?{insertId:42}:[];
const posted=await invoke('post /manga_danmu');assert.equal(posted.code,200);assert.equal(posted.data.user_id,7);assert.equal(posted.data.page_idx,0);assert.equal(posted.data.content,'Hello');assert.equal(posted.data.danmu_id,42);assert.equal(calls.length,2);assert.match(calls[0].sql,/a.is_draft = 0/);assert.match(calls[0].sql,/n.is_personal = 0/);assert.match(calls[0].sql,/n.is_banned = 0/);assert.match(calls[0].sql,/n.novel_type='manga'/);assert.deepEqual(calls[0].p,[11,7]);assert.deepEqual(calls[1].p,[7,7,11,0,'Hello']);console.log('PASS public manga/chapter/type/draft gate, authenticated sender, bounded trimmed content and committed insertion receipt without a second lookup')
for(const idx of [-1,1.5,2,'bad',undefined]){calls.length=0;assert.equal((await invoke('post /manga_danmu',{body:{novel_id:7,article_id:11,page_idx:idx,content:'Hi'}})).code,400);assert.equal(calls.filter(x=>x.sql.startsWith('INSERT')).length,0)}for(const content of ['',{},'x'.repeat(101)]){calls.length=0;assert.equal((await invoke('post /manga_danmu',{body:{novel_id:7,article_id:11,page_idx:0,content}})).code,400);assert.equal(calls.length,0)}query=async()=>[];calls.length=0;assert.equal((await invoke('post /manga_danmu')).code,404);assert.equal(calls.length,1);assert.equal((await invoke('get /manga_danmus')).code,404);console.log('PASS negative/fractional/out-of-range/missing page and invalid content rejected before insertion; private/unavailable scope cannot read or post')
query=async sql=>sql.includes('SELECT a.article_id')?[{content:'{"pages":[{},{}]}'}]:[{danmu_id:1}];calls.length=0;const list=await invoke('get /manga_danmus',{query:{id:7,articleId:11,pageIdx:1}});assert.equal(list.code,200);assert.deepEqual(calls[1].p,[7,11,2,1]);assert.match(calls[1].sql,/d.deleted=0 AND d.page_idx>=0 AND d.page_idx<\?/);assert.match(calls[1].sql,/ORDER BY d.danmu_id/);query=async()=>{throw Error('db')};assert.equal((await invoke('get /manga_danmus')).code,503);console.log('PASS parameterized complete/page-specific data excludes deleted/out-of-range rows; database outage is 503')
for(const user of [7,9,8]){query=async sql=>sql.startsWith('SELECT')?[{user_id:7,author_id:9}]:{affectedRows:1};calls.length=0;const deleted=await invoke('get /delete_manga_danmu',{query:{id:42},user:[{user_id:user}]});assert.equal(deleted.code,user===8?403:200);assert.equal(calls.length,user===8?1:2);if(user!==8){assert.match(calls[1].sql,/SET deleted=1/);assert.deepEqual(calls[1].p,[42])}}console.log('PASS actual author/owner soft deletion, other user denied before write')
}
main().catch(e=>{console.error(e);process.exitCode=1})
