// Actual transaction and route code with an isolated bank/catalog; never writes live accounts.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {createReadingTip}=require('../bin/createReadingTip');
function database(){const state={balances:{7:{user_id:7,log:100,apple:30,cropped_log:0},9:{user_id:9,log:0,apple:0,cropped_log:0}},records:[],messages:[],book:{novel_id:55,author_id:9,name:'Test world',novel_type:'world'},gift:{item_name:'Test gift',item_cost:10,is_log_free:'0'},calls:[],fail:'',missingBook:false};let queue=Promise.resolve();
 const transaction=work=>{const run=queue.catch(()=>{}).then(async()=>{const snapshot=JSON.stringify({balances:state.balances,records:state.records,messages:state.messages});try{return await work(async(sql,p)=>{state.calls.push({sql,p});if(state.fail&&sql.includes(state.fail))throw Error('isolated write failed');if(sql.startsWith('SELECT n.*')){assert.match(sql,/n.deleted = 0 AND n.is_personal = 0 AND n.is_banned = 0/);return state.missingBook?[]:[state.book]};if(sql.startsWith('SELECT * FROM tipping_list'))return state.gift?[state.gift]:[];if(sql.startsWith('INSERT IGNORE'))return{affectedRows:0};if(sql.includes('FOR UPDATE')){assert.deepEqual(p,[7,9]);assert.match(sql,/ORDER BY user_id FOR UPDATE/);return p.map(id=>({...state.balances[id]}))};if(sql.startsWith('UPDATE user_bank SET cropped_log')){state.balances[p[1]].cropped_log+=p[0];return{affectedRows:1}};if(sql.startsWith('UPDATE user_bank SET')){const resource=sql.includes('SET apple')?'apple':'log',payer=state.balances[p[1]];if(payer[resource]<p[2])return{affectedRows:0};payer[resource]-=p[0];return{affectedRows:1}};if(sql.startsWith('INSERT INTO tipping')){state.records.push(p);return{insertId:state.records.length}};if(sql.startsWith('INSERT INTO novel_fans_messages')){state.messages.push(p);return{affectedRows:1}};throw Error('Unexpected isolated query')})}catch(error){Object.assign(state,JSON.parse(snapshot));throw error}});queue=run;return run};return{state,transaction};}
const body={novel_id:55,item_name:'Test gift',item_amount:3,item_cost:10,resource_name:'log',from_id:999,message:'support'};
async function main(){
 let db=database(),result=await createReadingTip(body,7,db.transaction);assert.equal(result.total,30);assert.equal(result.resource,'log');assert.equal(result.authorIncome,15);assert.equal(db.state.balances[7].log,70);assert.equal(db.state.balances[9].cropped_log,15);assert.equal(db.state.records[0][0],7);assert.deepEqual(db.state.messages[0],[55,7,'support','support']);assert.equal(result.balance,70);
 db=database();db.state.gift.is_log_free='1';result=await createReadingTip({...body,item_amount:2,resource_name:'apple'},7,db.transaction);assert.equal(db.state.balances[7].apple,10);assert.equal(db.state.balances[7].log,100);assert.equal(db.state.balances[9].cropped_log,0);
 console.log('PASS auth-derived payer, catalogue price/currency incl. string flags, balance/record/income/message transaction and Apple gifts');
 for(const patch of [{item_amount:-1},{item_amount:1.5},{item_amount:10000},{novel_id:'bad'},{item_name:''},{message:'x'.repeat(51)}]){db=database();await assert.rejects(createReadingTip({...body,...patch},7,db.transaction),e=>e.status===400);assert.equal(db.state.calls.length,0)}
 for(const patch of [{item_cost:1},{resource_name:'cropped_log'},{resource_name:'apple'}]){db=database();await assert.rejects(createReadingTip({...body,...patch},7,db.transaction),e=>e.status===409);assert.equal(db.state.records.length,0);assert.equal(db.state.balances[7].log,100)}
 db=database();db.state.missingBook=true;await assert.rejects(createReadingTip(body,7,db.transaction),e=>e.status===404);db=database();await assert.rejects(createReadingTip(body,9,db.transaction),e=>e.status===403);db=database();db.state.gift=null;await assert.rejects(createReadingTip(body,7,db.transaction),e=>e.status===409);
 console.log('PASS invalid amounts/targets/messages rejected before writes, changed price/currency, unavailable/private work, self-tip and removed gift');
 for(const fail of ['INSERT INTO tipping','SET cropped_log','INSERT INTO novel_fans_messages']){db=database();db.state.fail=fail;await assert.rejects(createReadingTip(body,7,db.transaction));assert.equal(db.state.balances[7].log,100);assert.equal(db.state.balances[9].cropped_log,0);assert.equal(db.state.records.length,0);assert.equal(db.state.messages.length,0)}
 db=database();db.state.balances[7].log=40;const concurrent=await Promise.allSettled([createReadingTip(body,7,db.transaction),createReadingTip(body,7,db.transaction)]);assert.equal(concurrent.filter(r=>r.status==='fulfilled').length,1);assert.equal(concurrent.find(r=>r.status==='rejected').reason.status,402);assert.equal(db.state.balances[7].log,10);assert.equal(db.state.records.length,1);
 console.log('PASS downstream write rollback restores all bank/record/message state; locked concurrent tips cannot overdraw');
 const routes=new Map(),router={use(){}};for(const verb of ['get','post','put','delete'])router[verb]=(route,...handlers)=>routes.set(verb+' '+route,handlers.at(-1));const module={exports:{}};db=database();
 vm.runInNewContext(fs.readFileSync(require.resolve('../routes/library'),'utf8'),{module,exports:module.exports,console:{log(){}},require(name){if(name==='express')return{Router:()=>router};if(name.endsWith('sql.js'))return{query:async()=>[],withTransaction:db.transaction};if(name.includes('createReadingTip'))return{createReadingTip};if(name.includes('readingVisibility'))return require('../bin/readingVisibility');if(name.includes('message.js'))return{sendMsg:async()=>{throw Error('notification unavailable')}};return{};}});
 const response={code:200,status(code){this.code=code;return this},json(data){this.data=data}};await routes.get('post /tipping')({user:[{user_id:7}],body},response);assert.equal(response.code,200);assert.equal(response.data.success,true);assert.equal(response.data.cost,30);assert.equal(db.state.records.length,1);
 await routes.get('post /tipping')({user:[{user_id:7}],body:{...body,item_cost:1}},response);assert.equal(response.code,409);assert.equal(db.state.records.length,1);
 console.log('PASS actual route acknowledges committed tip despite notification failure and returns real charge/balance; validation status retained');
}
main().catch(error=>{console.error(error);process.exitCode=1});
