const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {createReaderTreeOperations}=require('../bin/readerTreeOperations');
function database(){
 const state={bank:{log:10,apple:2},trees:[{plant_id:31,user_id:7,treeType:'oak_island',tree_status:'结果',growth_val:100,is_gotten:0}],orbs:[{orb_id:1,user_id:7,plant_id:31,reward:6,status:'pending'},{orb_id:2,user_id:7,plant_id:31,reward:5,status:'pending'}],tasks:[{task_code:'daily_checkin',task_type:'daily',growth_reward:4,icon:''}],userTasks:[],calls:[],fail:'',ready:true};let queue=Promise.resolve();
 const transaction=work=>{const run=queue.catch(()=>{}).then(async()=>{const snapshot=JSON.stringify({bank:state.bank,trees:state.trees,orbs:state.orbs,userTasks:state.userTasks});try{return await work(async(sql,p)=>{
  state.calls.push({sql,p});if(state.fail&&sql.includes(state.fail))throw Error('isolated failure');
  if(sql.startsWith('INSERT IGNORE INTO user_bank'))return{affectedRows:0};
  if(sql.startsWith('SELECT log, apple')){assert.match(sql,/FOR UPDATE/);return[{...state.bank}]}
  if(sql.startsWith('SELECT plant_id FROM treeplant'))return state.trees.filter(t=>t.user_id===p[0]&&t.is_gotten===0).map(t=>({plant_id:t.plant_id}));
  if(sql.startsWith('SELECT * FROM treeplant')){assert.match(sql,/FOR UPDATE/);return state.trees.filter(t=>t.user_id===p[0]&&(!sql.includes('AND plant_id = ?')||t.plant_id===p[1])&&(!sql.includes('is_gotten = 0')||t.is_gotten===0)).sort((a,b)=>b.plant_id-a.plant_id).slice(0,1).map(t=>({...t}))}
  if(sql.startsWith('INSERT INTO treeplant')){const id=Math.max(...state.trees.map(t=>t.plant_id))+1;state.trees.push({plant_id:id,user_id:p[1],treeType:p[0],tree_status:p[2],growth_val:p[3],is_gotten:0});return{insertId:id,affectedRows:1}}
  if(sql.startsWith('SELECT * FROM tree_tasks'))return state.tasks.filter(t=>t.task_code===p[0]);
  if(sql.startsWith('SELECT * FROM user_tree_tasks'))return state.userTasks.filter(t=>t.user_id===p[0]&&t.task_code===p[1]);
  if(sql.startsWith('INSERT INTO user_tree_tasks')){state.userTasks.push({id:1,user_id:p[0],task_code:p[1],last_completed_at:p[2],is_completed:1});return{affectedRows:1}}
  if(sql.startsWith('UPDATE user_tree_tasks')){const row=state.userTasks.find(t=>t.id===p[1]);row.last_completed_at=p[0];row.is_completed=1;return{affectedRows:1}}
  if(sql.startsWith('UPDATE treeplant SET growth_val')){const tree=state.trees.find(t=>t.plant_id===p[2]&&t.user_id===p[3]&&t.is_gotten===0);if(!tree)return{affectedRows:0};tree.growth_val=p[0];tree.tree_status=p[1];return{affectedRows:1}}
  if(sql.startsWith('UPDATE treeplant SET is_gotten')){const tree=state.trees.find(t=>t.user_id===p[0]&&t.plant_id===p[1]&&t.is_gotten===0);if(!tree)return{affectedRows:0};tree.is_gotten=1;return{affectedRows:1}}
  if(sql.startsWith('UPDATE user_bank SET log = log +')){state.bank.log+=p[0];state.bank.apple+=p[1];return{affectedRows:1}}
  if(sql.startsWith('SELECT orb_id')){let rows=state.orbs.filter(o=>o.user_id===p[0]&&o.plant_id===p[1]&&o.status==='pending');if(sql.includes('AND orb_id = ?'))rows=rows.filter(o=>o.orb_id===p[2]);if(sql.includes('LIMIT ?'))rows=rows.slice(0,p.at(-1));return rows.map(o=>({...o}))}
  if(sql.startsWith('UPDATE tree_exp_orbs')){const all=state.orbs.filter(o=>o.user_id===p[0]&&o.status==='pending');if(sql.includes("SET status = 'collected'")){let count=0;for(const orb of all){if(orb.plant_id===p[1]&&p.slice(2).includes(orb.orb_id)){orb.status='collected';count++}}return{affectedRows:count}}for(const orb of all){if(sql.includes('expire_at IS NOT NULL')?orb.overdue:orb.plant_id===p[1])orb.status='expired'}return{affectedRows:0}}
  throw Error('Unexpected query: '+sql);
 })}catch(error){Object.assign(state,JSON.parse(snapshot));throw error}});queue=run;return run};
 const operations=createReaderTreeOperations({withTransaction:transaction,expReady:async()=>state.ready,settings:async()=>({collect_all_limit:50,max_growth:100}),normalizeTheme:t=>['oak_island','snow_spruce'].includes(t)?t:'oak_island',benefits:async()=>({multiplier:2,membership_name:'Super'}),sameDay:(a,b)=>new Date(a).toDateString()===new Date(b).toDateString(),rewardFor:(a,b)=>Math.round(a*b),random:()=>.5});return{state,transaction,operations};
}
async function main(){
 let db=database();let result=await db.operations.harvest({userId:7,plantId:31,collectPending:true});assert.deepEqual(result.rewards,{log:5,apple:2});assert.equal(result.collected_reward,11);assert.equal(db.state.trees[0].growth_val,111);assert.equal(db.state.trees[0].is_gotten,1);assert.deepEqual(db.state.bank,{log:15,apple:4});assert(db.state.orbs.every(o=>o.status==='collected'));assert.match(db.state.calls[1].sql,/user_bank.*FOR UPDATE/);const old=await db.operations.harvest({userId:7,plantId:31,collectPending:true});assert.equal(old.replayed,true);assert.equal(old.rewards,null);assert.deepEqual(db.state.bank,{log:15,apple:4});const planted=await db.operations.plant({userId:7,treeType:'snow_spruce'});assert.equal(planted.growth_val,11);assert.equal(planted.treeType,'snow_spruce');await db.operations.harvest({userId:7,plantId:31});assert.equal(db.state.trees[1].is_gotten,0);assert.deepEqual(db.state.bank,{log:15,apple:4});console.log('PASS atomic collected growth/resource/harvest, safe replay by old owned ID and carryover to themed next tree')
 db=database();const concurrent=await Promise.all([db.operations.harvest({userId:7,plantId:31}),db.operations.harvest({userId:7,plantId:31})]);assert.equal(concurrent.filter(x=>x.replayed).length,1);assert.deepEqual(db.state.bank,{log:15,apple:4});db=database();db.state.trees[0].is_gotten=1;const plants=await Promise.allSettled([db.operations.plant({userId:7}),db.operations.plant({userId:7})]);assert.equal(plants.filter(x=>x.status==='fulfilled').length,1);assert.equal(db.state.trees.filter(t=>!t.is_gotten).length,1);console.log('PASS serialized concurrent harvest grants once and concurrent plant creates only one active tree')
 for(const fail of ['UPDATE user_bank','SET is_gotten','SET growth_val','SET status = \'collected\'']){db=database();db.state.fail=fail;await assert.rejects(db.operations.harvest({userId:7,plantId:31,collectPending:true}));assert.deepEqual(db.state.bank,{log:10,apple:2});assert.equal(db.state.trees[0].growth_val,100);assert.equal(db.state.trees[0].is_gotten,0);assert(db.state.orbs.every(o=>o.status==='pending'))}db=database();db.state.trees[0].tree_status='种植';db.state.trees[0].growth_val=10;await assert.rejects(db.operations.harvest({userId:7,plantId:31}),e=>e.status===409);await assert.rejects(db.operations.harvest({userId:8,plantId:31}),e=>e.status===404);await assert.rejects(db.operations.harvest({userId:7,plantId:-1}),e=>e.status===400);assert.deepEqual(db.state.bank,{log:10,apple:2});console.log('PASS bank/tree/orb failure rolls everything back; growing, foreign and invalid trees never grant resources')
 db=database();result=await db.operations.collect({userId:7,plantId:31,orbId:1});assert.equal(result.reward,6);assert.equal(result.exp_orbs.length,1);await assert.rejects(db.operations.collect({userId:7,plantId:31,orbId:1}),e=>e.status===409);assert.equal(db.state.trees[0].growth_val,106);result=await db.operations.collect({userId:7,plantId:31});assert.equal(result.total_reward,5);assert.equal(db.state.trees[0].growth_val,111);db=database();db.state.orbs[0].overdue=true;result=await db.operations.collect({userId:7,plantId:31});assert.equal(result.total_reward,5);assert.equal(db.state.orbs[0].status,'expired');db=database();db.state.ready=false;await assert.rejects(db.operations.collect({userId:7,plantId:31}),e=>e.status===503);result=await db.operations.harvest({userId:7,plantId:31});assert.equal(result.rewards.log,5);console.log('PASS exact owned orb collection, no repeat growth, expiration, batch and absent optional schema harvest compatibility')
 db=database();const tasks=await Promise.allSettled([db.operations.task({userId:7,taskCode:'daily_checkin'}),db.operations.task({userId:7,taskCode:'daily_checkin'})]);assert.equal(tasks.filter(x=>x.status==='fulfilled').length,1);assert.equal(tasks.find(x=>x.status==='fulfilled').value.reward,8);assert.equal(db.state.trees[0].growth_val,108);assert.equal(db.state.userTasks.length,1);db=database();db.state.fail='SET growth_val';await assert.rejects(db.operations.task({userId:7,taskCode:'daily_checkin'}));assert.equal(db.state.userTasks.length,0);assert.equal(db.state.trees[0].growth_val,100);console.log('PASS membership-scaled daily reward/completion commit together, duplicate claim cannot reward twice and rollback keeps task claimable')
 let queryFailure=false;const routes=new Map(),router={};for(const verb of ['get','post'])router[verb]=(name,...handlers)=>routes.set(verb+' '+name,handlers.at(-1));db=database();const module={exports:{}};vm.runInNewContext(fs.readFileSync(require.resolve('../routes/treePlant'),'utf8'),{module,exports:module.exports,console:{log(){}},Date,Math,Intl,require(name){if(name==='express')return{Router:()=>router};if(name.endsWith('sql.js'))return{query:async()=>{if(queryFailure)throw Error('read failed');return[]},withTransaction:(...args)=>db.transaction(...args)};if(name.includes('readerTreeOperations'))return{createReaderTreeOperations};return{};}});const res={status(code){this.code=code;return this},json(value){this.data=value},end(value){this.data=value}};await routes.get('post /reader_harvest')({user:[{user_id:7}],body:{},query:{}},res);assert.equal(res.code,400);assert.equal(db.state.calls.length,0);await routes.get('post /reader_harvest')({user:[{user_id:7}],body:{plant_id:31,user_id:8},query:{}},res);assert.equal(res.data.success,true);assert.equal(db.state.bank.log,15);db=database();await routes.get('get /got_tree')({user:[{user_id:7}],body:{},query:{}},res);assert.match(res.data,/已收获，获得原木 × 5/);assert.equal(routes.has('post /reader_collect_orbs'),true);queryFailure=true;let responses=0;const failedRes={status(code){this.code=code;return this},json(value){responses++;this.data=value}};await routes.get('get /get_treePlant_of')({user:[{user_id:7}],query:{}},failedRes);assert.equal(failedRes.code,503);assert.equal(responses,1);console.log('PASS actual registered desktop route requires owned tree ID and auth user; legacy mobile harvest keeps text protocol')
}
main().catch(error=>{console.error(error);process.exitCode=1});
