const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {createReaderTreeOperations}=require('../bin/readerTreeOperations');
const plain=x=>JSON.parse(JSON.stringify(x));
function setup(){
 const state={trees:[{plant_id:31,user_id:7,is_gotten:0,growth_val:42,tree_status:'开花',treeType:'oak_island'}],bank:{log:10,apple:2},daily:[{id:1,user_id:7,task_code:'exp_read_time',date_key:'2026-10-10',progress_value:570,completed_times:0}],metrics:{},membership:'',post:0,reply:0,orbs:[{orb_id:1,user_id:7,plant_id:31,reward:5,status:'pending'}],tasks:[{task_code:'exp_read_time',task_name:'阅读累计',source_code:'read_seconds',required_value:600,daily_limit:3,exp_reward:6,is_enabled:1},{task_code:'exp_write_time',task_name:'写作累计',source_code:'write_seconds',required_value:600,daily_limit:3,exp_reward:8,is_enabled:1}],fail:'',outsideWrites:0,calls:[],evalFail:false,now:'2026-10-10T03:00:00Z'};let queue=Promise.resolve(),inTransaction=0;
 const q=async(raw,p=[])=>{const sql=raw.replace(/\s+/g,' ').trim();state.calls.push({sql,p,inTransaction});if(state.fail&&sql.includes(state.fail))throw Error('isolated injected failure');if(!inTransaction&&/^(UPDATE|INSERT)/.test(sql)){state.outsideWrites++;throw Error('write outside transaction')}
 if(sql.startsWith('INSERT IGNORE INTO user_bank'))return{affectedRows:0};
 if(sql.startsWith('SELECT log, apple')){assert.match(sql,/FOR UPDATE/);return[{...state.bank}]}
 if(sql.startsWith('SELECT * FROM treeplant'))return state.trees.filter(t=>t.user_id===p[0]&&(!sql.includes('plant_id = ?')||t.plant_id===p[1])&&(!sql.includes('is_gotten = 0')||!t.is_gotten)).sort((a,b)=>b.plant_id-a.plant_id).slice(0,1).map(plain);
 if(sql.startsWith('SELECT plant_id FROM treeplant'))return state.trees.filter(t=>t.user_id===p[0]&&!t.is_gotten);
 if(sql.startsWith('INSERT INTO treeplant')){const id=Math.max(...state.trees.map(t=>t.plant_id))+1;state.trees.push({plant_id:id,user_id:p[1],treeType:p[0],tree_status:p[2],growth_val:p[3],is_gotten:0});return{insertId:id,affectedRows:1}}
 if(sql.startsWith('UPDATE treeplant SET growth_val')){const tree=state.trees.find(t=>t.plant_id===p[2]&&t.user_id===p[3]&&!t.is_gotten);if(!tree)return{affectedRows:0};tree.growth_val=p[0];tree.tree_status=p[1];return{affectedRows:1}}
 if(sql.startsWith('UPDATE treeplant SET is_gotten')){const tree=state.trees.find(t=>t.user_id===p[0]&&t.plant_id===p[1]&&!t.is_gotten);if(!tree)return{affectedRows:0};tree.is_gotten=1;return{affectedRows:1}}
 if(sql.startsWith('UPDATE user_bank SET log')){state.bank.log+=p[0];state.bank.apple+=p[1];return{affectedRows:1}}
 if(sql.startsWith('SELECT membership_type'))return state.membership?[{membership_type:state.membership}]:[];
 if(sql.startsWith('SELECT setting_key'))return[];
 if(sql.includes('FROM tree_exp_tasks'))return state.tasks.map(plain);
 if(sql.includes('FROM tree_exp_orbs')&&sql.includes('LIMIT 1'))return[];
 if(sql.startsWith('SELECT orb_id'))return state.orbs.filter(o=>o.user_id===p[0]&&o.plant_id===p[1]&&o.status==='pending').map(plain);
 if(sql.startsWith('UPDATE tree_exp_orbs')){if(sql.includes("SET status = 'collected'")){const rows=state.orbs.filter(o=>o.user_id===p[0]&&o.plant_id===p[1]&&p.slice(2).includes(o.orb_id)&&o.status==='pending');rows.forEach(o=>o.status='collected');return{affectedRows:rows.length}}if(sql.includes('expire_at IS NOT NULL'))return{affectedRows:0};state.orbs.filter(o=>o.user_id===p[0]&&o.plant_id===p[1]&&o.status==='pending').forEach(o=>o.status='expired');return{affectedRows:1}}
 if(sql.includes('FROM user_tree_exp_task_daily')){if(!sql.includes('WHERE'))return[];let rows=state.daily.filter(r=>r.user_id===p[0]);if(sql.includes('task_code IN (?)'))rows=rows.filter(r=>r.date_key===p[1]&&p[2].includes(r.task_code));else rows=rows.filter(r=>r.task_code===p[1]&&(!sql.includes('date_key = ?')||r.date_key===p[2]));return rows.map(plain)}
 if(sql.startsWith('INSERT INTO user_tree_exp_task_daily')){const row={id:state.daily.length+1,user_id:p[0],task_code:p[1],date_key:p[2],progress_value:p[3],completed_times:p[4]||0};assert(!state.daily.some(r=>r.user_id===row.user_id&&r.task_code===row.task_code&&r.date_key===row.date_key),'duplicate key');state.daily.push(row);return{affectedRows:1}}
 if(sql.startsWith('UPDATE user_tree_exp_task_daily')){const row=state.daily.find(r=>r.id===p.at(-1));assert(row);if(sql.includes('completed_times = completed_times +')){row.completed_times+=p[0];row.progress_value=p[1]}else if(sql.includes('progress_value = progress_value +'))row.progress_value+=p[0];else row.progress_value=p[0];return{affectedRows:1}}
 if(sql.startsWith('INSERT INTO user_metric_daily')){const key=sql.includes('read_seconds')?'read_seconds':'write_seconds';state.metrics[key]=(state.metrics[key]||0)+p[2];return{affectedRows:1}}
 if(sql.includes('FROM achievement_definitions')){if(state.evalFail)throw Error('badge service failed');return[]}
 if(sql.includes('FROM comm_posts'))return[{count:state.post}];if(sql.includes('FROM comm_comments'))return[{count:state.reply}];
 if(sql.includes('FROM tree_tasks')||sql.includes('FROM user_tree_tasks'))return[];
 throw Error('unexpected SQL: '+sql)};
 const tx=work=>{const run=queue.catch(()=>{}).then(async()=>{const snapshot=plain({trees:state.trees,bank:state.bank,daily:state.daily,metrics:state.metrics,orbs:state.orbs});inTransaction++;try{return await work(q)}catch(error){Object.assign(state,snapshot);throw error}finally{inTransaction--}});queue=run;return run};
 const achievementModule={exports:{}};vm.runInNewContext(fs.readFileSync(require.resolve('../bin/achievements'),'utf8'),{module:achievementModule,exports:achievementModule.exports,console:{log(){}},Date,Intl,require(name){if(name.endsWith('sql.js'))return{query:q};return{}}});
 const routes=new Map(),router={get:(p,...h)=>routes.set('get '+p,h.at(-1)),post:(p,...h)=>routes.set('post '+p,h.at(-1))},module={exports:{}};
 const code=fs.readFileSync(require.resolve('../routes/treePlant'),'utf8')+'\nmodule.exports.check={settleExpTaskRewards,applyGrowthReward,buildExpTaskStates};';
 const FixedDate=class extends Date{constructor(...args){super(...(args.length?args:[state.now]))}static now(){return new Date(state.now).getTime()}};
 vm.runInNewContext(code,{module,exports:module.exports,console:{log(){}},Date:FixedDate,Intl,Math,require(name){if(name==='express')return{Router:()=>router};if(name==='node:crypto')return require(name);if(name.endsWith('sql.js'))return{query:q,withTransaction:tx};if(name.includes('readerTreeOperations'))return{createReaderTreeOperations};if(name.includes('achievements'))return achievementModule.exports;return{}}});
 const settings={max_growth:100,timezone:'Asia/Shanghai'},settle=(tree=null,options={})=>module.exports.check.settleExpTaskRewards(7,tree,settings,options),report=async(seconds=30,id='read-isolated-report-1',activity='read_seconds')=>{const res={status(code){this.code=code;return this},json(value){this.data=value;return this}};await routes.get('post /report_exp_activity')({user:[{user_id:7}],body:{seconds,activity_type:activity,...(id==null?{}:{client_request_id:id})}},res);return res};
 const treeOps=createReaderTreeOperations({withTransaction:tx,expReady:async()=>true,settings:async()=>({collect_all_limit:50,max_growth:100}),normalizeTheme:t=>t||'oak_island',benefits:async()=>({multiplier:1}),sameDay:()=>false,rewardFor:n=>n,random:()=>.5});return{state,settle,report,treeOps,check:module.exports.check,settings};
}
async function main(){
 let db=setup();const two=await Promise.all([db.report(30,'read-isolated-report-1'),db.report(30,'read-isolated-report-2')]);assert.equal(two.reduce((n,r)=>n+r.data.total_reward,0),6);assert.equal(db.state.daily[0].progress_value,630);assert.equal(db.state.daily[0].completed_times,1);assert.equal(db.state.trees[0].growth_val,48);assert.equal(db.state.metrics.read_seconds,60);assert.equal(db.state.outsideWrites,0);console.log('PASS actual concurrent duration routes accumulate without lost seconds, settle once and commit metric/task/growth together');
 db=setup();db.state.daily[0].progress_value=1200;db.state.membership='super';const results=await Promise.all([db.settle(plain(db.state.trees[0])),db.settle(plain(db.state.trees[0]))]);assert.equal(results.reduce((n,r)=>n+r.total_reward,0),24);assert.equal(db.state.daily[0].completed_times,2);assert.equal(db.state.trees[0].growth_val,66);assert(db.state.calls.filter(c=>c.sql.startsWith('SELECT * FROM treeplant')&&c.inTransaction).every(c=>/FOR UPDATE/.test(c.sql)));console.log('PASS concurrent refresh uses freshly locked owned tree and membership-scaled reward only once');
 db=setup();db.state.trees[0].growth_val=96;db.state.daily[0].progress_value=600;await Promise.all([db.settle(plain(db.state.trees[0])),db.treeOps.collect({userId:7,plantId:31})]);assert.equal(db.state.trees[0].growth_val,107);assert.equal(db.state.trees[0].tree_status,'结果');assert.equal(db.state.orbs[0].status,'collected');console.log('PASS automatic tasks and explicit orb collection share lock order and neither overwrites the other growth');
 for(const fail of ['INSERT INTO user_metric_daily','completed_times = completed_times +','UPDATE treeplant SET growth_val']){db=setup();db.state.fail=fail;let out=await db.report();assert.equal(out.code,503);assert.equal(db.state.daily[0].progress_value,570);assert.equal(db.state.daily[0].completed_times,0);assert.equal(db.state.trees[0].growth_val,42);assert.deepEqual(db.state.metrics,{})}db=setup();db.state.fail='INSERT INTO user_tree_exp_task_daily';const failed=await db.report();assert.equal(failed.code,503);assert.equal(db.state.daily[0].progress_value,570);assert.deepEqual(db.state.metrics,{});db.state.fail='';assert.equal((await db.report()).data.total_reward,6);console.log('PASS metric, task marker, growth or durable receipt failure rolls back full report and allows exactly one later award');
 db=setup();const first=await db.report();assert.equal(first.data.total_reward,6);const repeat=await db.report();assert.equal(repeat.data.replayed,true);assert.equal(repeat.data.total_reward,0);assert.equal(repeat.data.settled_tasks.length,0);assert.equal(db.state.daily[0].progress_value,600);assert.equal(db.state.metrics.read_seconds,30);assert.equal((await db.report(31)).code,409);assert.equal((await db.report(30,'read-isolated-report-1','write_seconds')).code,409);const duplicated=await Promise.all([db.report(30,'read-isolated-report-2'),db.report(30,'read-isolated-report-2')]);assert.equal(duplicated.filter(r=>r.data.replayed).length,1);assert.equal(db.state.daily[0].progress_value,630);db.state.now='2026-10-11T03:00:00Z';assert.equal((await db.report(30,'read-isolated-report-1')).data.replayed,true);assert.equal(db.state.daily.filter(row=>row.task_code==='exp_read_time').length,1);assert.equal(db.state.metrics.read_seconds,60);console.log('PASS lost-response and concurrent same-ID retries count once; altered duration/type rejected without new progress or toast');
 db=setup();db.state.daily[0].progress_value=10000;let result=await db.settle();assert.equal(result.total_reward,18);assert.equal((await db.settle()).total_reward,0);db=setup();const stale=plain(db.state.trees[0]);db.state.trees[0].is_gotten=1;db.state.trees.push({...stale,plant_id:32,growth_val:0});result=await db.settle(stale);assert.equal(result.has_active_tree,false);assert.equal(db.state.daily[0].completed_times,0);assert.equal(db.state.trees[1].growth_val,0);db.state.trees[1].is_gotten=1;await db.report();assert.equal(db.state.daily[0].progress_value,600);assert.equal(db.state.daily[0].completed_times,0);await db.treeOps.plant({userId:7});assert.equal((await db.settle()).total_reward,6);console.log('PASS daily limit, stale harvested tree cannot credit a new tree; unplanted progress settles on later planting');
 db=setup();db.state.evalFail=true;const accepted=await db.report();assert.equal(accepted.data.msg,'ok');assert.equal(accepted.data.total_reward,6);assert.equal((await db.report()).data.replayed,true);assert.equal(db.state.metrics.read_seconds,30);for(const seconds of [0,301,1.5,true,-1,[],[30],{},null])assert.equal((await db.report(seconds,'read-valid-report-other')).code,400);assert.equal((await db.report(30,'short')).code,400);assert.equal((await db.report(30,'read-valid-report-other','community_post')).code,400);db=setup();const legacy=await db.report(30,null);assert.equal(legacy.data.msg,'ok');assert.equal(legacy.data.total_reward,6);assert.equal(legacy.data.client_request_id,undefined);console.log('PASS badge evaluation failure cannot undo accepted report, strict input precedes writes and legacy mobile response stays compatible');
}
main().catch(error=>{console.error(error);process.exitCode=1});
