// Execute real Express route handlers against an isolated query double; no DB connection.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
let query;const sqlCalls=[];
function routeFile(file){const routes=new Map(),router={use(){}};for(const verb of ['get','post','put','delete'])router[verb]=(url,...handlers)=>routes.set(`${verb} ${url}`,handlers.at(-1));const module={exports:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../routes',file),'utf8'),{module,exports:module.exports,console:{log(){},error(){}},require(name){if(name==='express')return{Router:()=>router};if(name.endsWith('sql.js'))return{query:async(sql,params)=>{sqlCalls.push({sql,params:Array.from(params||[])});return query(sql,params)}};if(name.includes('avatarFrames'))return{decorateRows:async rows=>{for(const row of rows)row.avatar_frame={asset_url:'https://example.invalid/frame.png'}}};if(name.includes('userPrivacy'))return{listGuard:()=>()=>{}};if(name.includes('SECRET'))return{SECRET:'isolated-test-only'};return{};}},{filename:file});return routes;}
const response=()=>({code:200,status(n){this.code=n;return this},json(data){this.data=data;return this},end(data){this.data=JSON.parse(data)}});
async function invoke(routes,key,patch={}){const res=response();await routes.get(key)({query:{},body:{},params:{},user:[{user_id:7}],...patch},res);return res;}
async function main(){
 const stickers=routeFile('community/stickers.js');query=async(sql)=>sql.includes('COUNT(*) as total')?[{total:1}]:[{sticker_id:1,is_private:1,is_favorite:1}];
 sqlCalls.length=0;const favorites=await invoke(stickers,'get /favorites',{query:{page:'2',limit:'20'}});assert.equal(favorites.data.stickers[0].is_private,true);assert.equal(favorites.data.pagination.page,2);assert.equal(sqlCalls.length,2);
 for(const call of sqlCalls){assert.match(call.sql,/sf.user_id = \? AND \(s.is_private = 0 OR s.user_id = \?\)/);assert.deepEqual(call.params.slice(0,2),[7,7]);}assert.deepEqual(sqlCalls[1].params,[7,7,20,20]);
 sqlCalls.length=0;await invoke(stickers,'get /',{query:{url:'https://image.invalid/a.png'}});for(const call of sqlCalls){assert.match(call.sql,/s.url = \?/);assert.match(call.sql,/\(s.user_id = \? OR s.is_private = 0\)/);assert.ok(call.params.includes(7));assert.ok(call.params.includes('https://image.invalid/a.png'));assert.doesNotMatch(call.sql,/LIMIT/);}
 console.log('PASS actual favorites and URL lookup SQL restrict private stickers to owner, parameterized counts and pagination');
 let writes=0;query=async sql=>{if(sql.includes('FROM stickers'))return[{sticker_id:1,user_id:8,is_private:1}];writes++;return{affectedRows:1};};assert.equal((await invoke(stickers,'post /favorites',{body:{sticker_id:1}})).code,403);assert.equal(writes,0);
 query=async sql=>{if(sql.includes('FROM stickers'))return[{sticker_id:1,user_id:7,is_private:1}];if(sql.includes('SELECT * FROM sticker_favorites'))return[];writes++;return{affectedRows:1};};assert.equal((await invoke(stickers,'post /favorites',{body:{sticker_id:1}})).code,201);assert.equal(writes,1);
 query=async sql=>sql.includes('FROM stickers')?[{sticker_id:1,user_id:8,is_private:0}]:sql.includes('SELECT * FROM sticker_favorites')?[{sticker_id:1}]:{affectedRows:1};assert.equal((await invoke(stickers,'post /favorites',{body:{sticker_id:1}})).code,400);
 assert.equal((await invoke(stickers,'put /:id',{params:{id:1},body:{is_private:true}})).code,403);assert.equal((await invoke(stickers,'delete /:id',{params:{id:1}})).code,403);
 console.log('PASS private-other favorite rejected before write; own private favorite allowed; duplicate and owner mutation authorization retained');
 const community=routeFile('community.js');query=async(sql,params)=>{assert.deepEqual(Array.from(params),['11']);assert.match(sql,/CASE WHEN requested.reply_to_id = -1 THEN requested.essay_comment_id ELSE requested.father_comment_id END/);assert.match(sql,/requested.deleted = 0 AND n.deleted = 0 AND n.reply_to_id = -1/);assert.match(sql,/LEFT JOIN article_cento/);return[{essay_comment_id:10,novel_id:7,article_id:3,cento_id:8,cento_item_id:8,cento_article_id:3,cento_paragraph_id:2,cento_paragraph:'quoted text',cento_user_id:7,media_urls:'["https://image.invalid/a.png"]',user_id:7}];};
 const located=await invoke(community,'get /novel_comment_from_comment_id',{query:{comment_id:'11'}});assert.equal(located.data[0].essay_comment_id,10);assert.equal(located.data[0].cento.paragraph_id,2);assert.equal(located.data[0].cento.paragraph,'quoted text');assert.equal(located.data[0].cento_item_id,undefined);assert.equal(located.data[0].media_urls.length,1);assert.ok(located.data[0].avatar_frame);
 query=async()=>[];assert.equal((await invoke(community,'get /novel_comment_from_comment_id',{query:{comment_id:404}})).data.length,0);
 console.log('PASS real notification route resolves reply/root with deletion guards and returns paragraph/media/frame; missing target stays empty');
}
main().catch(error=>{console.error(error);process.exitCode=1});
