<template><span class="reader-tip"><button class="tip-trigger" @click="open">打赏</button><el-dialog custom-class="reading-dialog" :title="`支持《${book.name}》`" :visible.sync="visible" width="min(630px, 94vw)" append-to-body :close-on-click-modal="!submitting" :close-on-press-escape="!submitting" :show-close="!submitting">
  <p v-if="loading" class="tip-status" role="status">正在确认礼物与资源余额…</p><p v-if="error" class="tip-error" role="alert">{{ error }}</p><button v-if="!ready&&!loading" class="reload" @click="load">重新加载</button>
  <template v-if="ready"><div class="resource-balances"><span>原木 <strong>{{ balances.log }}</strong></span><span>苹果 <strong>{{ balances.apple }}</strong></span><nuxt-link :to="resourceGuide">如何获取原木</nuxt-link></div><div class="gift-grid" aria-label="选择礼物"><button v-for="gift in gifts" :key="gift.item_name" :class="{selected:selectedName===gift.item_name}" :aria-pressed="selectedName===gift.item_name" :disabled="submitting||completed" @click="selectedName=gift.item_name"><img v-if="safeImage(gift.img_url)" :src="safeImage(gift.img_url)" alt="" /><span>{{ gift.item_name }}</span><small>{{ gift.item_cost }} {{ Number(gift.is_log_free)===1?'苹果':'原木' }}</small></button></div>
    <div class="amount-row"><label>数量 <input v-model.number="amount" type="number" min="1" max="9999" step="1" :disabled="submitting||completed" /></label><div class="quick-amounts"><button v-for="value in [1,5,10,66,99,520]" :key="value" :disabled="submitting||completed" @click="amount=value">×{{ value }}</button></div></div><label class="tip-message">粉丝留言 <textarea v-model="message" maxlength="50" rows="2" :disabled="submitting||completed" placeholder="写下对作品的支持，最多 50 字" /></label><div class="tip-total"><span>总计 <strong>{{ total }}</strong> {{ resource==='apple'?'苹果':'原木' }}</span><small v-if="resource==='log'">作者获得 {{ Math.floor(total/2) }} 原木收益</small></div><p v-if="uncertain" class="tip-error">请求结果未确认，请先查看余额和粉丝榜，确认后再操作。</p><p v-if="notice" class="tip-status">{{ notice }}</p></template>
  <span slot="footer"><el-button :disabled="submitting" @click="visible=false">关闭</el-button><el-button type="primary" :loading="submitting" :disabled="!ready||loading||!validAmount||!selected||uncertain||completed" @click="confirm">确认打赏</el-button></span>
</el-dialog></span></template>
<script>
import { readingToken } from '~/plugins/api/reading'
import { worldImage } from '~/utils/reader-world'
import { loginReturnPath } from '~/utils/login-return'
export default {
 props:{book:{type:Object,required:true}},data:()=>({visible:false,ready:false,loading:false,submitting:false,gifts:[],selectedName:'',balances:{log:0,apple:0},profile:null,amount:1,message:'',error:'',notice:'',uncertain:false,completed:false,version:0,account:null}),
 computed:{selected(){return this.gifts.find(item=>item.item_name===this.selectedName)},validAmount(){return Number.isSafeInteger(Number(this.amount))&&Number(this.amount)>0&&Number(this.amount)<=9999},resource(){return this.selected&&Number(this.selected.is_log_free)===1?'apple':'log'},total(){return this.selected&&this.validAmount?Number(this.selected.item_cost)*Number(this.amount):0},resourceGuide(){return'/read/resources'}},
 watch:{visible(value){if(!value)this.reset()},'book.novel_id'(){this.visible=false;this.reset()}},mounted(){this.account=readingToken();window.addEventListener('focus',this.checkAccount);window.addEventListener('storage',this.checkAccount)},beforeDestroy(){this.version++;window.removeEventListener('focus',this.checkAccount);window.removeEventListener('storage',this.checkAccount)},
 methods:{safeImage:worldImage,current(version,token,id){return version===this.version&&token===readingToken()&&Number(id)===Number(this.book.novel_id)&&this.visible},checkAccount(){if(this.account!==readingToken()){this.account=readingToken();this.visible=false;this.reset()}},reset(){this.version++;this.ready=false;this.loading=false;this.submitting=false;this.gifts=[];this.balances={log:0,apple:0};this.profile=null;this.message='';this.amount=1;this.selectedName='';this.error=this.notice='';this.uncertain=false;this.completed=false},
 open(){this.checkAccount();if(!readingToken()){this.$router.push({path:'/login',query:{redirect:loginReturnPath(this.$route.fullPath)}});return}this.reset();this.account=readingToken();this.visible=true;this.load()},
 async load(){if(this.loading||this.submitting||!readingToken())return;const version=++this.version,token=readingToken(),id=this.book.novel_id;this.loading=true;this.ready=false;this.error='';try{const[gifts,balances,profile,fan]=await Promise.all([this.$api.reader.gifts(),this.$api.reader.balances(),this.$api.reader.profile(),this.$api.reader.ownFanMessage(id).catch(()=>null)]);if(!this.current(version,token,id))return;const person=Array.isArray(profile)?profile[0]:profile;if(!person||!person.user_id)throw new Error('无法确认当前账号，请重新登录');if(Number(person.user_id)===Number(this.book.author_id||this.book.auther_id||this.book.creator_id))throw new Error('不能给自己的作品打赏');const balance=Array.isArray(balances)?balances[0]:balances;if(!balance||!Number.isFinite(Number(balance.log))||!Number.isFinite(Number(balance.apple)))throw new Error('资源余额加载失败');this.profile=person;this.balances={log:Number(balance.log),apple:Number(balance.apple)};this.gifts=(Array.isArray(gifts)?gifts:[]).filter(g=>g&&g.item_name&&Number.isSafeInteger(Number(g.item_cost))&&Number(g.item_cost)>0).sort((a,b)=>Number(a.sort_id)-Number(b.sort_id));if(!this.gifts.length)throw new Error('暂无可用礼物');this.selectedName=this.gifts[0].item_name;this.message=fan&&fan.success?String(fan.message||'').slice(0,50):'';this.ready=true}catch(error){if(this.current(version,token,id))this.error=error.message||'打赏信息加载失败'}finally{if(version===this.version)this.loading=false}},
 async confirm(){if(this.submitting||!this.ready||!this.selected||!this.validAmount||this.uncertain||this.completed)return;const token=readingToken(),version=this.version,id=this.book.novel_id;if(!token||token!==this.account){this.checkAccount();return}const gift=this.selected,amount=Number(this.amount),resource=this.resource,total=this.total;if(this.balances[resource]<total){this.error=`${resource==='apple'?'苹果':'原木'}余额不足`;return}this.submitting=true;this.error=this.notice='';const message=this.message.trim();try{const result=await this.$api.reader.tip({from_id:Number(this.profile.user_id),novel_id:Number(id),item_name:gift.item_name,item_amount:amount,item_cost:Number(gift.item_cost),resource_name:resource,message});if(!this.current(version,token,id))return;if(result!=='success'&&(!result||result.success!==true)){this.uncertain=true;throw new Error('服务未确认打赏结果，请先核对余额与粉丝榜')}this.balances[resource]=result&&typeof result.balance==='number'?result.balance:Math.max(0,this.balances[resource]-total);this.$emit('tipped',{gift,amount,total,resource});this.$message.success(`已打赏 ${amount} 个${gift.item_name}`);this.notice='打赏已完成。';this.completed=true;
   if(result==='success'&&message){try{const saved=await this.$api.reader.fanMessage(id,message);if(!saved.success)throw new Error('留言未保存')}catch(_){if(this.current(version,token,id))this.notice='打赏已完成；留言未保存，可在粉丝榜中编辑。'}}
  }catch(error){if(this.current(version,token,id)){this.error=error.message||'打赏请求失败';if(!error.status)this.uncertain=true}}finally{if(version===this.version)this.submitting=false}}
 }
}
</script>
<style scoped>.reader-tip{display:inline-flex}.tip-trigger,.reload{border:1px solid #e0d6c7;border-radius:6px;padding:9px 16px;background:#fff;color:#947358;font:inherit;font-size:13px;cursor:pointer}.tip-status,.tip-error{font-size:13px;line-height:1.8;color:#9e8a6e;margin-bottom:12px}.tip-error{color:#b96550}.resource-balances{display:flex;align-items:center;gap:20px;padding:14px 16px;border-radius:8px;background:#f8f6f0;font-size:13px;color:#9f8b70}.resource-balances strong{color:#746046;margin-left:8px}.resource-balances a{margin-left:auto;color:#869655;font-size:12px;text-decoration:none}.gift-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:20px 0}.gift-grid button{border:1px solid #e5ddcf;border-radius:9px;background:#fff;padding:12px 8px;display:flex;align-items:center;flex-direction:column;gap:8px;color:#8b7559;font:inherit;font-size:13px;cursor:pointer}.gift-grid button.selected{background:#f0f4e5;border-color:#a6b57f}.gift-grid img{height:48px;width:48px;object-fit:contain}.gift-grid small{font-size:11px;color:#a99576}.amount-row{display:flex;gap:14px;align-items:center;flex-wrap:wrap;margin:18px 0}.amount-row label{font-size:13px;color:#9d8a6f}.amount-row input{width:75px;border:1px solid #dfd5c6;border-radius:5px;padding:7px;margin-left:8px;font:inherit;color:#857058}.quick-amounts{display:flex;gap:5px;flex-wrap:wrap}.quick-amounts button{border:1px solid #e3dccf;background:#fff;border-radius:5px;color:#998368;font-size:11px;cursor:pointer;padding:6px 8px}.tip-message{display:grid;gap:8px;font-size:13px;color:#9c8a70}.tip-message textarea{font:inherit;font-size:13px;box-sizing:border-box;width:100%;resize:vertical;line-height:1.8;border:1px solid #e0d6c8;border-radius:7px;padding:10px;color:#7d674b}.tip-total{display:flex;align-items:center;gap:10px;flex-wrap:wrap;border-top:1px solid #ece5d9;margin-top:18px;padding:18px 0;font-size:13px;color:#968165}.tip-total strong{color:#82974f;font-size:20px;margin-left:10px}.tip-total small{margin-left:auto;font-size:11px;color:#b19e81}button:disabled{opacity:.5;cursor:default}button:focus-visible{outline:2px solid #8fa365;outline-offset:2px}@media(max-width:600px){.gift-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.resource-balances{gap:12px;flex-wrap:wrap}.resource-balances a{margin-left:0}}
</style>
